baseurl = "https://sound.ml"
title = "sound.ml"
languageCode = "ja"
paginate = 10
Copyright = "sound.ml 2017"
canonifyurls = true
theme = "casper"

[params]
description = ""
cover = "images/cover.jpg"
logo = "images/logo.png"
googleAnalyticsUserID = "UA-44406328-7"

githubName = "matsuoshi"
twitterName = "matsuoshi"

author = "matsuoshi"
authorlocation = "Kobe, Japan"
authorwebsite = "https://sound.ml/"
#bio= "my bio"
# Optional RSS-Link, if not provided it defaults to the standard index.xml
#RSSLink = "http://feeds.feedburner.com/..."
# facebookName = ""
# linkedinName = ""
# set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
hideHUGOSupport = false

[params.social]
#twitter = "your_twitter"
