title = "monaural"
baseurl = "https://monaural.net/"
theme = "pause"
paginate = 24
googleAnalytics = "UA-44406328-7"


[author]
name = "matsuoshi"
image = "/media/avatar.jpg"


[permalinks]
post = "/post/:year:month/:filename/"


[params]
description = "monaural | 音楽などのメモブログ"
ogpimage = "/images/thumbnail.png"
newerPosts = "newer"
olderPosts = "older"


[params.links]
Playlists = "/tags/playlist/"

[social]
facebook-square = "https://facebook.com/matsuoshi"
twitter-square = "https://twitter.com/matsuoshi"
github = "https://github.com/matsuoshi"
instagram = "https://instagram.com/matsuoshi"
lastfm-square = "http://www.last.fm/user/matsuoshi"
mixcloud = "https://www.mixcloud.com/matsuoshi/"
spotify = "https://open.spotify.com/user/matsuoshi"
