baseurl = "https://pause.cf/"
title = "pause"
paginate = 10
googleAnalytics = "UA-44406328-7"


[permalinks]
post = "/post/:year:month/:filename/"


[params]
description = "strike a pause"
newerPosts = "< newer"
olderPosts = "older >"


[social]
facebook-square = "https://facebook.com/matsuoshi"
twitter-square = "https://twitter.com/matsuoshi"
github = "https://github.com/matsuoshi"
instagram = "https://instagram.com/matsuoshi"
lastfm-square = "http://www.last.fm/user/matsuoshi"
mixcloud = "https://www.mixcloud.com/matsuoshi/"
