title = "pause"
baseurl = "https://pause.cf/"
theme = "pause"
paginate = 24
googleAnalytics = "UA-44406328-7"


[author]
name = "matsuoshi"
image = "//avatars.githubusercontent.com/u/73213?s=32"


[permalinks]
post = "/post/:year:month/:filename/"


[params]
description = "pause.cf | 音楽などのメモブログ"
ogpimage = "/images/thumbnail.png"
newerPosts = "newer"
olderPosts = "older"


[params.links]
Playlists = "/tags/playlist/"

[social]
facebook-square = "https://facebook.com/matsuoshi"
twitter-square = "https://twitter.com/matsuoshi"
github = "https://github.com/matsuoshi"
instagram = "https://instagram.com/matsuoshi"
lastfm-square = "http://www.last.fm/user/matsuoshi"
mixcloud = "https://www.mixcloud.com/matsuoshi/"
